name: EnhancedDebugStick-WorldGuard
version: ${project.version}
main: com.njdaeger.enhanceddebugstick.worldguard.WG_Impl
api-version: 1.16
depend:
  - EnhancedDebugStick
  - WorldGuard
authors: [ NJDaeger ]
